language: python
sudo: false
dist: xenial
python:
   - "3.6"
   - "3.7"
   - "3.8"
env:
   - DJANGO='django>=2.2,<3.0' TESTDB=sqlite
   - DJANGO='django>=2.2,<3.0' TESTDB=postgres
   - DJANGO='django>=3.0,<3.1' TESTDB=sqlite
   - DJANGO='django>=3.0,<3.1' TESTDB=postgres
   - DJANGO='https://github.com/django/django/archive/master.tar.gz' TESTDB=sqlite
   - DJANGO='https://github.com/django/django/archive/master.tar.gz' TESTDB=postgres

matrix:
   allow_failures:
      - env: DJANGO='https://github.com/django/django/archive/master.tar.gz' TESTDB=postgres
      - env: DJANGO='https://github.com/django/django/archive/master.tar.gz' TESTDB=sqlite

services:
   - postgresql

cache:
  directories:
    - $HOME/.cache/pip

before_install:
   - if [ "$TESTDB" = "postgres" ]; then pip install -q psycopg2 ; fi
# command to install dependencies,
install:
   - pip install -r requirements.txt
   - pip install "$DJANGO"
# command to run tests
script: NOSE_WITH_COVERAGE=1 NOSE_COVER_PACKAGE=pyconza python manage.py test
